sudo: required
services:
  - docker

before_install:
  - docker build -t rahadyan/kodekurawal-web-test -f ./Dockerfile.dev --build-arg REACT_APP_BASE_URL=REACT_APP_BASE_URL --build-arg REACT_APP_API_URL=REACT_APP_API_URL --build-arg REACT_APP_BASE_URL=REACT_APP_BASE_URL .

script:
  - docker run rahadyan/kodekurawal-web-test npm test

after_success:
  - docker build -t rahadyan/kodekurawal-web --build-arg REACT_APP_BASE_URL=REACT_APP_BASE_URL --build-arg REACT_APP_API_URL=REACT_APP_API_URL --build-arg REACT_APP_BASE_URL=REACT_APP_BASE .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rahadyan/kodekurawal-web

branches:
  only:
    - master