FROM node:12
ENV CI=true
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
COPY ./env.sh .
COPY .env.example .
RUN chmod +x env.sh
CMD ["/bin/bash", "-c", "/usr/src/app/env.sh","npm","run","dev" ]

